[build]
builder = "nixpacks"
buildCommand = "npm install"

[deploy]
startCommand = "node server.js"
healthcheckPath = "/"
healthcheckTimeout = 180
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5

[nixpacks]
nodeVersion = "18"

[variables]
PORT = "5000"
NODE_ENV = "production"