[build]
builder = "nixpacks"
buildCommand = "npm install"

[deploy]
startCommand = "node server.js"
healthcheckPath = "/"
healthcheckTimeout = 180
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5

[phases.setup]
nixPkgs = ["nodejs", "npm"]

[nixpacks]
nodeVersion = "18"

[environments.production]
port = 5000
NODE_ENV = "production"